core/urls.py
from django.conf.urls import url

from . import views

app_name = 'core'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^reviews/$', views.reviews, name='reviews'),
    url(r'^services/$', views.services, name='services'),
    url(r'^portfolio/warehouse/$', views.warehouse, name='warehouse'),
    url(r'^portfolio/office/$', views.office, name='office'),
    url(r'^portfolio/building/$', views.building, name='building'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^about/$', views.about, name='about'),
    url(r'^testimonials/$', views.testimonials, name='testimonials'),
    ]

src/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('core.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

class ContactForm(forms.Form):
    auto_id=False
    name = forms.CharField(max_length=128, label="",widget=forms.TextInput(attrs={'id':'name','placeholder':"name",}))
    email = forms.EmailField(max_length=128,label="",widget=forms.TextInput(attrs={'id':'email','placeholder':"email"}))
    number = forms.CharField(max_length=128, label="",widget=forms.TextInput(attrs={'id':'number','placeholder':"phone number",}))
    CHOICES = (('residential','residential'),('commercial','commercial'))
    select = forms.ChoiceField(choices=CHOICES,label="",widget=forms.Select(attrs={'id':'select'}))
    description = forms.CharField(max_length=128,label="",widget=forms.Textarea(attrs={'id':'description','rows':'6','placeholder':'Description of project and any additional info'}))

core/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.core.mail import send_mail

from .forms import ContactForm

# Create your views here.

def index(request):
    template = "core/index.html"
    context = {}
    return render(request,template,context)

def portfolio(request):
    template = "core/portfolio.html"
    context = {}
    return render(request,template,context)

def reviews(request):
    template = "core/reviews.html"
    context = {}
    return render(request,template,context)

def services(request):
    template = "core/services.html"
    context = {}
    return render(request,template,context)

def warehouse(request):
    template = "core/warehouse.html"
    context = {}
    return render(request,template,context)

def office(request):
    template = "core/office.html"
    context = {}
    return render(request,template,context)

def building(request):
    template = "core/building.html"
    context = {}
    return render(request,template,context)

def thanks(request):
    template = "core/thanks.html"
    context = {}
    return render(request,template,context)

def about(request):
    template = "core/about.html"
    context = {}
    return render(request,template,context)

def testimonials(request):
    template = "core/testimonials.html"
    context = {}
    return render(request,template,context)


def contact(request):
     # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            number = form.cleaned_data['number']
            select = form.cleaned_data['select']
            description = form.cleaned_data['description']
            message = '%s\n%s\n%s\n%s\n%s\n' %(name,number, email,select,description)
            emailTo = 'xxmrmau5@gmail.com'
            send_mail('contact from WPC',message,"rob",['johnathan@wpcdesigns.com','xxmrmau5@gmail.com'])


            # redirect to a new URL:
            return redirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm(auto_id=False)

    template = "core/contact.html"
    context = {'form' : form}
    return render(request,template,context)

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
		<article id="one" class="spotlight about odd accent3">
				<div class="inner">
<header class="major top-margin">
						<h2>About Us</h2>
					</header>

	          <div class="content">
						    <h3>Owners and Founders<br> Johnathan Hausmann and Shelby Stoughton</h3>
						    <p>We believe your home, office or business is a reflection of you and that your floor can create a positive first impression when people walk in your door. Our goal at WPC is to provide you with that statement floor that gives you a “wow” factor. We have chosen to work in the communities we live so our reputation is very important to us.  Our business model is based on personal references which means your satisfaction is the most important aspect of our job.  We have satisfied customers because we insure our product meets your needs first and foremost.  Educated clients are happy so we take the time to evaluate your needs in person, survey the area where flooring will be done, discuss what your vision is and develop a comprehensive plan based on these factors.  We both have strong ethical backgrounds that we take pride in.  We were raised with the expectations of honesty, attention to detail, and doing things correctly the first time. These core values are how we operate our business today.  Communication, transparency in pricing and service insure your peace of mind and that you will not only like your new floor and your experience with WPC, you will love it! </p>
					</div>
	          
			</article>

		<!-- Spotlight -->

		<!-- Spotlight -->

		<!-- Carousel -->

		<!-- Posts -->
{% include "core/cform.html" %}

{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Woodland's Polished Concrete</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>

	<body>

		<!-- Header -->
			<header id="header">
				<a class="logo" href="{% url 'core:index' %}"><img class="conimg" src="{% static 'WPC.jpg' %}"/> </a>
				<nav id="vis-menu">
            <!-- well this is an interesting tag, why is it empty? thats because i decided
                 that it would be better to build this menu in javascript for some reason
                 and that was a bad decision and i should feel bad. but its the only way
                 that it works now and thats the baggage that i have to bear.-->
            <!-- the function is addDesktopMenu in main.js and don't laugh at me for this code quailty -->
        </nav>

      </header>

		<!-- Menu -->
			<nav id="menu">
          <ul class="links">
			        <li><a href="{% url 'core:index' %}">Home</a></li>
					    <li><a href="{% url 'core:about' %}">About</a></li>
					    <li><a href="{% url 'core:services' %}">Services</a></li>
					    <li><a href="{% url 'core:testimonials' %}">Testimonials</a></li>
					    <li><a href="{% url 'core:portfolio' %}">Portfolio</a></li>
					    <li><a href="#">(979) 571-3064</a></li>
					    <li><a href="#">Johnathan@wpcdesigns.com</a></li>
			        <li><a href="#">The Woodlands Tx United States 77380</a></li>
					    <li><a href="{% url 'core:contact' %}" class="button special">Contact</a></li>
          </ul>

			</nav>


        {% block content %}
        {% endblock %}

		<!-- Footer -->
			<footer id="footer">
				<ul class="contact-icons">
					<li class="icon fa-map-marker"><a href="#">The Woodlands Tx United States 77380</a></li>
					<li class="icon fa-phone"><a href="#">(979) 571-3064</a></li>
					<li class="icon fa-envelope"><a href="#">Johnathan@wpcdesigns.com</a></li>
            <li><!--Proview Badge Code Start --><a href="http://www.thebluebook.com/iProView/0" style="text-decoration:none; color:inherit;" target="_blank"><img src="http://www.thebluebook.com/assets/img/badges/proview-badge-lg.png?qp=0" border="0" title="Qualify Us Now! ProView" alt="Qualify Us Now! ProView" height="58" width="182" hspace="0" vspace="0" /></a><!--Proview Badge Code END -->
            </li>
            <li class="icon" >
                <a href="http://www.homeadvisor.com/rated.WoodlandsPolished.67072627.html" style=""><img alt="Rated & Reviewed HomeAdvisor Pro" style="" src="http://www.homeadvisor.com/images/sp-badges/soap-solid-border.png?sp=67072627&key=25430d5f9b1378f9406333592699f681" /></a>

            </li>
				</ul>
				<div class="copyright">
					&copy; 2018. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/skel.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

core/templates/core/building.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
			<section id="four" class="wrapper style4">
				<div class="inner">
					<header class="major">
						<h2>Stained Concrete</h2>
					</header>
					<div class="carousel">
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/building-7.jpg' %}" alt="" />
							</div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/building-8.jpg' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image4.JPG' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image6.JPG' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image7.JPG' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image9.JPG' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image11.JPG' %}" alt="" />
							  </div>
						</article>
						<article>
							  <div class="image" data-position="top center">
								    <img src="{% static 'images/building/image12.JPG' %}" alt="" />
							  </div>
						</article>
						<nav>
							<a href="#" class="previous"><span class="label">Previous</span></a>
							<a href="#" class="next"><span class="label">Next</span></a>
						</nav>
					</div>
				</div>
			</section>

{% endblock %}

core/templates/core/cform.html
<section id="six" class="wrapper style1">

				<div class="inner">
					<header class="major">
						<h2>Contact Us</h2>
						<p>Fill this fom out for a free quote!</p>
					</header>

          <form method="post" action="http://207.148.2.38:8000/contact/">
              {% csrf_token %}
							<div class="row uniform">
									<div class="6u 12u$(xsmall)">
											<input class="alt" type="text" name="name" id="name" value="" placeholder="Name" />
									</div>
									<div class="6u$ 12u$(xsmall)">
											<input class="alt" type="text" name="text" id="number" value="" placeholder="Phone Number" />
									</div>
									<div class="12u$">
											<input class="alt" type="email" name="email" id="email" value="" placeholder="Email" />
                  </div>
									<div class="12u">
												<select class="alt" name="select" id="select">
													<option value="">- Project Type -</option>
													<option value="residential">Residential</option>
													<option value="commercial">Commercial</option>
												</select>
                  </div>

									<div class="12u">
                      <textarea class="alt" name="description" cols="40" rows="6" placeholder="Description of project and any additional info" maxlength="128" required="" id="description"></textarea>
                  </div>
									<!-- Break -->
									<div class="12u$">
											<ul class="actions align-center">
												  <li><input onclick="store()" type="submit" value="Send Message" class="button accent4 special" /></li>
											</ul>
									</div>
							</div>
					</form>
				</div>
</section>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<section id="main" class="wrapper alt contact">
		<div class="inner">

				<header class="major">
						<h1>Contact Us</h1>
				</header>

				<div class="row 200%">
						<div class=" 12u">

							  <!-- Text -->
							  <!-- Form -->
                <div class="align-center">
								    <h3>Complete the form below to recieve a free quote</h3>
                </div>


								<hr />

                <form action="/contact/" method="post">
                    {% csrf_token %}
                    
							<div class="row uniform">
									<div class="6u 12u$(xsmall)">
                    {{ form.name }}
									</div>
									<div class="6u$ 12u$(xsmall)">
                    {{ form.number }}
									</div>

									<div class="12u">
                    {{ form.email }}
                  </div>
									<div class="12u">
                    {{ form.select }}
                  </div>

									<div class="12u">
                    {{ form.description }}
                  </div>
									<div class="12u$">
											<ul class="actions">
												  <li><input id="submit" type="submit" value="Send Message" class="button accent4 special" /></li>
											</ul>
										</div>
                </form>
            </div>
        </div>
    </div>
</section>

<script>
 function addValues(){
     if (localStorage.getItem("name") === null) {
         console.log("no items");
         return null
     }
     var name = document.getElementById("name");
     var email = document.getElementById("email");
     var number = document.getElementById("number");
     var select = document.getElementById("select");
     var description = document.getElementById("description");

     name.value = localStorage.getItem("name");
     email.value = localStorage.getItem("email");
     number.value = localStorage.getItem("number");
     select.value = localStorage.getItem("select");
     description.value = localStorage.getItem("description");
     document.getElementById("submit").click();
     localStorage.clear();
 }
 document.addEventListener("DOMContentLoaded", addValues());

</script>

{% endblock %}

core/templates/core/generic.html
<!DOCTYPE HTML>
<!--
	Cascade by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html>
	<head>
		<title>Untitled</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<a class="logo" href="index.html">Cascade <span>by Pixelarity</span></a>
				<nav>
					<ul>
						<li>
							<a href="#menu">Menu</a>
						</li>
					</ul>
				</nav>
			</header>

		<!-- Menu -->
			<nav id="menu">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="generic.html">Generic</a></li>
					<li><a href="elements.html">Elements</a></li>
					<li><a href="#" class="button special">Sign Up</a></li>
					<li><a href="#" class="button">Log In</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<section id="main" class="wrapper">
				<div class="inner">

					<header class="major">
						<h1>Generic</h1>
					</header>

					<span class="image main"><img src="images/pic04.jpg" alt="" /></span>
					<p>Vis accumsan feugiat adipiscing nisl amet adipiscing accumsan blandit accumsan sapien blandit ac amet faucibus aliquet placerat commodo. Interdum ante aliquet commodo accumsan vis phasellus adipiscing. Ornare a in lacinia. Vestibulum accumsan ac metus massa tempor. Accumsan in lacinia ornare massa amet. Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan.</p>
					<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan commodo odio cubilia ac eu interdum placerat placerat arcu commodo lobortis adipiscing semper ornare pellentesque.</p>
					<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet blandit adipiscing arcu ante.</p>

				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<ul class="contact-icons">
					<li class="icon fa-map-marker"><a href="#">1234 Fictional Street #5432 Nashville, TN 00000-0000</a></li>
					<li class="icon fa-phone"><a href="#">(000) 000-0000</a></li>
					<li class="icon fa-envelope"><a href="#">info@untitled.tld</a></li>
				</ul>
				<div class="copyright">
					&copy; Untitled. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
		<!-- Banner -->
			<section id="banner">
          <div class="container" >
              <div class="row title-of-banner" >
                  <div class="6u 12u(medium)" >
                      <div class="inner " >
					                <h1>Woodlands<br />
					                    Polished<br />
					                    Concrete &amp Design</h1>
                      </div>
                  </div>

                  <div class="-1u 12u$(medium) 5u$" >
                      {% include "core/cform.html" %}
                  </div>
              </div>
          </div>

			</section>

		  <!-- Spotlight -->
	    
			<article id="one" class="spotlight odd accent1">
				  <div class="inner" id="home-spot">
					    <div class="image" data-position="top right">
						      <img src="{% static 'images/offer.JPG' %}" alt="" />
					    </div>
					    <h2>What we <br /> have to offer</h2>
					    <div class="content">
                  <p>Woodlands Polished Concrete & Design provides Polished Concrete, Epoxy Floor Systems, Decorative Concrete, Surface Preparation & Flooring Removal to Houston and surrounding areas. WPC services residential, commercial and industrial markets. Let us bring your design to life! </p>
						      <ul class="actions">
							        <li><a href="{% url 'core:services' %}" class="button special accent1">Learn more</a></li>
						</ul>
					</div>
				</div>
			</article>

		<!-- Spotlight -->

		<!-- Spotlight -->

		<!-- Carousel -->

		<!-- Posts -->

{% endblock %}
row-reverse

core/templates/core/portfolio.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

			<section id="five" class="wrapper">

				<div class="inner">
					<header class="major">
						<h2>Portfolio</h2>
					</header>
					<div class="posts">
						<article>
							  <a href="{% url 'core:warehouse' %}" class="image"><img src="{% static 'images/warehouse/warehouse-1.jpg' %}" alt="" /></a>
							  <div class="content">
								    <h3><a href="{% url 'core:warehouse' %}">Polished Concrete</a></h3>
								    <ul class="actions">
									      <li><a href="{% url 'core:warehouse' %}" class="button special accent1">View More</a></li>
								    </ul>
							  </div>
						</article>
						<article>
							  <a href="{% url 'core:office' %}" class="image"><img src="{% static 'images/office/building-3.jpg' %}" alt="" /></a>
							  <div class="content">
								    <h3><a href="{% url 'core:office' %}">Counter Tops</a></h3>
								<ul class="actions">
									  <li><a href="{% url 'core:office' %}" class="button special accent1">View More</a></li>
								</ul>
							</div>
						</article>
						<article>
							  <a href="{% url 'core:building' %}" class="image"><img src="{% static 'images/building/building-7.jpg' %}" alt="" /></a>
							  <div class="content">
								    <h3><a href="{% url 'core:building' %}">Stained Concrete</a></h3>
								    <ul class="actions">
									      <li><a href="{% url 'core:building'  %}" class="button special accent1">View more</a></li>
								</ul>
							</div>
						</article>
					</div>
				</div>
			</section>
		  <!-- Spotlight -->

		<!-- Spotlight -->

		<!-- Spotlight -->

		<!-- Carousel -->

		<!-- Posts -->

{% include "core/cform.html" %}
		<!-- CTA -->

{% endblock %}

core/templates/core/reviews.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
			<section id="five" class="wrapper">
				<div class="inner">
					<header class="major">
						<h2>Some of our customer reviews</h2>
					</header>
					<div class="posts">
						<article>
							<a href="#" class="image"><img src="images/pic07.jpg" alt="" /></a>
							<div class="content">
								<h3><a href="#">Sed faucibus</a></h3>
								<p>Sed egestas, ante et vulputate lorem ipsum sed dolor sit amet Morbi purus sed libero, faucibus adipiscing, commodo quis. Lorem ipsum dolor sit amet nullam sed adipiscing.</p>
								<ul class="actions">
									<li><a href="#" class="button special accent1">Learn more</a></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="#" class="image"><img src="images/pic08.jpg" alt="" /></a>
							<div class="content">
								<h3><a href="#">Morbi commodo</a></h3>
								<p>Sed egestas, ante et vulputate lorem ipsum sed dolor sit amet Morbi purus sed libero, faucibus adipiscing, commodo quis. Lorem ipsum dolor sit amet nullam sed adipiscing.</p>
								<ul class="actions">
									<li><a href="#" class="button special accent2">Learn more</a></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="#" class="image"><img src="images/pic09.jpg" alt="" /></a>
							<div class="content">
								<h3><a href="#">Tempus lorem</a></h3>
								<p>Sed egestas, ante et vulputate lorem ipsum sed dolor sit amet Morbi purus sed libero, faucibus adipiscing, commodo quis. Lorem ipsum dolor sit amet nullam sed adipiscing.</p>
								<ul class="actions">
									<li><a href="#" class="button special accent3">Learn more</a></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="#" class="image"><img src="images/pic10.jpg" alt="" /></a>
							<div class="content">
								<h3><a href="#">Libero adipiscing</a></h3>
								<p>Sed egestas, ante et vulputate lorem ipsum sed dolor sit amet Morbi purus sed libero, faucibus adipiscing, commodo quis. Lorem ipsum dolor sit amet nullam sed adipiscing.</p>
								<ul class="actions">
									<li><a href="#" class="button special accent4">Learn more</a></li>
								</ul>
							</div>
						</article>
					</div>
				</div>
			</section>
		<!-- CTA -->
{% include "core/cform.html" %}


{% endblock %}

core/templates/core/services.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
			<article id="zero" class="spotlight odd " style="background-color:#272727;">
              <header class="major top-margin">
						      <h2 style="color:#ffffff;">Services</h2>
					    </header>

			</article>
		  <!-- Spotlight -->
			<article id="one" class="spotlight odd accent1">
				  <div class="inner">
					    <div class="image" data-position="top right">
						      <img src="{% static 'images/services/polish.JPG' %}" alt="" />
					    </div>
					    <h2>Polished <br />
					        Concrete</h2>
					    <div class="content">
                  <p>From new concrete to existing concrete WPC can transform ones concrete slab into a one of a kind floor. Polished concrete involves several stages of mechanically grinding your concrete floor with specialized diamond tooling. Through each stage of concrete grinding, the pores of the concrete surface gradually close resulting in a harder and shinier floor. In addition, we add a concrete impregnating densifier and sealer that soaks into the concrete, hardens and becomes part of the polished concrete floor. </p>
					</div>
				</div>
			</article>

		<!-- Spotlight -->
			<article id="two" class="spotlight even accent2">
				<div class="inner">
					  <div class="image" data-position="top left">
						    <img src="{% static 'images/services/image1.JPG' %}" alt="" />
					</div>
					<h2>Decorative<br />
					Concrete</h2>
					<div class="content">
              <p>Woodlands Polished Concrete & Design wants to bring your design to life. Looking to add a little extra to your already unique floor? We can help through dyes, stains, custom boarders, etching and logos.  Our clients are our number one priority, and we will go the extra mile to make sure you are complete satisfied with our work. </p>
					</div>
				</div>
			</article>

		<!-- Spotlight -->
			<article id="three" class="spotlight odd accent3">
				<div class="inner">
					  <div class="image" data-position="center right">
						    <img id="epoxy" src="{% static 'images/services/epoxy.jpg' %}" alt="" />
					</div>
					<h2>Epoxy<br />
					Floor System</h2>
					<div class="content">
						  <p>Epoxy floor coatings work well in business settings where high-traffic and frequent chemical and biological spills are expected. Epoxy floor systems are coatings that bond directly to the surface and offer long-term protection. Depending on the clients needs, flakes and slip-resistant materials can be added to protect your customers and employees from unwanted falls. Epoxy floors work well in warehouses, airplane hangers, commercial kitchens, factories, medical facilities, automotive shops, etc. 
              </p>
					</div>
				</div>
			</article>

		<!-- Carousel -->

		<!-- Posts -->

		<!-- CTA -->
{% include "core/cform.html" %}


{% endblock %}

core/templates/core/testimonials.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<article id="one" class="spotlight about odd accent3">
		<div class="inner">
        <header class="major  top-margin">
						<h2>Testimonials</h2>
				</header>
        <div class="testimonial">
            <div class="center-text"><h1>Zachary Brackin</h1></div>
            <div>Communication and scheduling. Company did exactly what they said they were going to do at an excellent price. Unparraled work ethic that is hard to find these days. They did an excellent job at limiting dust and getting exactly what we wanted. We could not have asked for a better experience. If you ever want to talk about my experience let me know and I will give talk about this great group. Thank you for the excellence work.
            </div>
            <hr/>
        </div>
        <div class="testimonial">
            <div class="center-text"><h1>Jodi Jackson</h1></div>
            <div>We absolutely love our floors! Johnathon is very thorough and walks you through every step of the way. There still are people and companies out there that are honest and have integrity! Highly recommend.
            </div>
            <hr/>
        </div>
        <div class="testimonial">
            <div class="center-text"><h1>Tim Vigus
            </h1></div>
            <div>Most professional and respectful guy our business has had the pleasure of working with! Highly recommend for any services!
            </div>
            <hr/>
        </div>
        <div class="testimonial">
            <div class="center-text"><h1>Tracy T.
            </h1></div>
            <div>Wonderful job on our floors. Our home was flooded and old flooring after removal provided extra challenges. Johnathan and his team were fantastic to work with.
            </div>
            <hr/>
        </div>
        <div class="testimonial">
            <div class="center-text"><h1>Jim D.
            </h1></div>
            <div>excellent work and great workers. very professional. Johnathan and the others we meet were great and outstanding attitude.
            </div>
            <hr/>
        </div>
        <div class="testimonial">
            <div class="center-text"><h1>Kyle B.
            </h1></div>
            <div>Johnathan and his team did a great job and stands behind their work.
            </div>
            <hr/>
        </div>
	      
</article>

<!-- Spotlight -->

<!-- Spotlight -->

<!-- Carousel -->

<!-- Posts -->
{% include "core/cform.html" %}

{% endblock %}

core/templates/core/thanks.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

			<section id="main" class="wrapper alt">
				<div class="inner">

					<header class="major">
						<h1>Thanks! We'll get back to you as soon as possible</h1>
					</header>
        </div>
      </section>

{% endblock %}